---
- name: initialize function
  include_tasks: includes/init.yaml

- name: collect platform capabilities as facts
  nxos_capabilities:

- name: run command and parse output
  include_tasks: run_cli.yaml
  vars:
    nxos_command: "{{ item.command }}"
    nxos_parser: "cli/{{ item.parser }}"
    nxos_parser_engine: "{{ item.engine | default('command_parser') }}"
    nxos_run_cli_command_pre_hook: "{{ item.pre_hook | default(None) }}"
    nxos_run_cli_command_post_hook: "{{ item.post_hook | default(None) }}"
  loop: "{{ lookup('file', nxos_get_facts_command_map) | from_yaml }}"
  when: nxos_get_facts_subset |  intersect(item.groups)
